import { Controller, Get } from '@nestjs/common';
import { ExperienceEntry } from 'shared/types';

@Controller('api/experience')
export class ExperienceController {
  @Get()
  getExperience(): Promise<ExperienceEntry[]> {
    return Promise.resolve([
      {
        id: '1',
        role: 'Team Lead - Checkout Platform Reliability',
        company: 'Getty Images',
        description: '',
        bulletPoints: [
          'Responsible for ensuring consistence quality and reliability of an E-Commerce platform that processes several hundred million in revenue per year globally across multiple sites.',
          'Support three active production tracks to ensure new features are built and deployed with intended impact to the customer experience in a scalable manner.',
          'Deliver platform intended to support all transactions across four high traffic sites (Getty Images, iStock) in preparation for a large merger',
          'Provided mentorship and direct coaching to developers at multiple levels of development',
          'Built custom migration support RMQ/Redis/S3 Service to support safe migration',
          'Introduced Mock Service Worker functionality to fully support Jest based integration testing of complex subsystem',
          'Implemented significant improvements to monitoring and debugging utilities',
        ],
        startDate: '2025-04-01',
        endDate: null,
        tags: [
          'TypeScript',
          'React',
          'React-Query',
          'Ruby on Rails',
          'NestJS',
          'Splunk',
          'Grafana',
        ],
      },
      {
        id: '2',
        role: 'Technical Architect / Technical Lead / Project Manager - Checkout Migration',
        company: 'Getty Images',
        description: '',
        bulletPoints: [
          'Delivered a complete migration of Checkout Platform from AngularJS to React / React-Query / NestJS / TypeScript',
          'Led a variably sized team of developers (2-6), establishing priorities, managing timelines and ensuring quality of deliverables',
          'Provided mentorship and direct coaching to developers at multiple levels of development',
          'Developed implementation plan, including architecture, for a complete rewrite of the checkout front-end platform',
          'Ensured minimal disruption to the customer experience during the migration process',
          'Managed external stakeholders to ensure alignment on project goals and timelines',
        ],
        startDate: '2024-05-01',
        endDate: '2025-04-01',
        tags: [
          'JavaScript',
          'React',
          'Node.js',
          'AngularJS',
          'Ruby on Rails',
          'Splunk',
          'Grafana',
        ],
      },
      {
        id: '3',
        role: 'Platform Engineer - V2 Migration',
        company: 'Getty Images',
        description: '',
        bulletPoints: [],
        startDate: '2024-01-01',
        endDate: '2024-05-01',
        tags: ['JavaScript', 'React', 'Node.js'],
      },
      {
        id: '4',
        role: 'Front End Technical Lead - Generative AI Imagery',
        company: 'Getty Images',
        description: '',
        bulletPoints: [],
        startDate: '2023-04-01',
        endDate: '2024-01-01',
        tags: ['JavaScript', 'React', 'Node.js'],
      },
      {
        id: '5',
        role: 'Front End Technical Lead - Payment Instruments',
        company: 'Getty Images',
        description: '',
        bulletPoints: [],
        startDate: '2022-08-01',
        endDate: '2023-04-01',
        tags: ['JavaScript', 'React', 'Node.js'],
      },
      {
        id: '6',
        role: 'Front End Technical Lead - Customer Acquisition',
        company: 'Getty Images',
        description: '',
        bulletPoints: [
          'Introduced Cypress Platform prototype for reliable end-to-end testing',
        ],
        startDate: '2021-08-01',
        endDate: '2022-08-01',
        tags: ['JavaScript', 'React', 'Node.js', 'Cypress'],
      },
      {
        id: '7',
        role: 'Senior Front End Developer - Customer Retention',
        company: 'Getty Images',
        description: '',
        bulletPoints: [],
        startDate: '2021-05-01',
        endDate: '2021-08-01',
        tags: ['JavaScript', 'React', 'Node.js'],
      },
      {
        id: '8',
        role: 'Senior Front End Developer - Customer Retention (Contract)',
        company: 'Getty Images',
        description: '',
        bulletPoints: [],
        startDate: '2020-11-15',
        endDate: '2021-05-01',
        tags: ['JavaScript', 'React', 'Node.js'],
      },
      {
        id: '9',
        role: 'Software Developer',
        company: 'H&R Block Canada',
        description:
          'Transferred from the User Experience team to join the Software Development group in a full-time capacity as the role was better aligned with my skillset. In this capacity my work has centered around the implementation of newer features / monetization channels and developing flexible architecture to support evolving business requirements.',
        bulletPoints: [
          'Delivered first internal react application to prototype stage',
          'Completed Migration of Enterprise software from Grunt Taskrunners to Webpack / Babel configuration, allowing full integration of modern ESLINT / ECMA2015+ standards as part of a long-term migration plan (AngularJS to React/Redux, Angular)',
          'Architected large scale new feature development',
          'Manage task prioritization within highly distributed team, including offshore resources',
          'Active contributor to all parts of agile development process',
        ],
        startDate: '2017-01-01',
        endDate: '2020-01-01',
        tags: ['JavaScript', 'React', 'Node.js'],
      },
      {
        id: '10',
        role: 'User Experience Researcher – Contract',
        company: 'H&R Block Canada',
        description:
          'Worked as one of the first designers on a new User Experience team within the organization to completely reinvent the company’s digital do-it-yourself tax software. In this capacity I conducted many in person and remote usability testing sessions and worked actively to redevelop the UI, both in a design and front-end developer capacity.',
        bulletPoints: [
          'Improved overall NPS score from 34 to 65 in year one',
          'Maintained NPS in year two while converting to a monetization strategy that delivered revenue growth of 400% while maintaining consistent year over year growth in users',
          'Pioneered A/B Testing within organization for the purpose of maximizing both customer conversion and desired actions (Optimizely / Wasabi)',
        ],
        startDate: '2015-01-01',
        endDate: '2017-01-01',
        tags: ['UX Design', 'User Research'],
      },
    ]);
  }
}
